FROM node:18-alpine
WORKDIR /usr/src/app

# install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --only=production || npm install --production

# copy app
COPY . .

EXPOSE 3000
CMD ["node","server.js"]
